export const PATHS = {
  HOME: '/',
  SWAP: '/swap',
  LIQUIDITY: '/liquidity',
  CREATE_LIQUIDITY: '/create',
  ADD_LIQUIDITY: '/add',
  ADDA_LIQUIDITY: '/add/:currencyIdA',
  ADDAB_LIQUIDITY: '/add/:currencyIdA/:currencyIdB',
  REMOVE_LIQUIDITY: '/remove/:tokens',
  REMOVEAB_LIQUIDITY: '/remove/:currencyIdA/:currencyIdB',
  MINT: '/mint',
  MINT_TBCC_NFT: '/mint/tbcc-nft-token',
  ANALYTICS: '/analytics',
  BURN: '/burn',
  BURN_RATING: '/burn/rating',
  LOTTERY: '/lottery',
  GAME: '/uragame',
  GAME_MAIN: '/uragame/main',
  GAME_MAIN_INVITER: '/uragame/main/:inviterAddress',
  GAME_STATS: '/uragame/stats',
  GAME_BONUSES: '/uragame/bonuses',
  GAME_RULES: '/uragame/rules',
  FARMS: '/farms',
  NFT: '/admin-nft',
  TEAM:'/team',
  CLAIM: '/claim',
  CLAIM_YOURS: '/claim/yours',
  VODA: '/voda-nft'
}
